### ISSUE TITLE
Initial install breakage

### ISSUE THREAD

**Issue by Edozie101** [OSVR/Homebrew-OSVR#1]
Error: osvr/osvr/osvr-core is a head-only formula
Install with `brew install --HEAD osvr/osvr/osvr-core

It would be good to change the Readme to include this

**Comment by d235j** [comment]
Yeah, I noticed this last night after it was too late for me to fix it.
Fixed in https://github.com/OSVR/Homebrew-OSVR/commit/5fad9872d9c3eed8289f861b7f418b754dce5cc4.
