### ISSUE TITLE
cannot install on OS X 10.10.5

### ISSUE THREAD

**Issue by alexandrovsky** [OSVR/Homebrew-OSVR#3]
$ brew install osvr-core --HEAD
Error: undefined method `desc' for Formulary::Formulae::OsvrCore:Class
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/osvr/homebrew-osvr/osvr-core.rb:2:in`class:OsvrCore'
/usr/local/Library/Taps/osvr/homebrew-osvr/osvr-core.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in`module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in`klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in`factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in`map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in`install'
/usr/local/Library/brew.rb:140:in `<main>'

**Comment by gching** [comment]
Do a `brew update`. This solved it for me.

**Comment by d235j** [comment]
@alexandrovsky have you resolved this problem? This seems to be due to very outdated Homebrew; if you updated and still cannot install, please let us know.

**Comment by d235j** [comment]
Closing — assumed this is resolved. Please comment or open a new issue if you are still having problems.
