### ISSUE TITLE
  Could not find a package configuration file provided by "jsoncpp" with any

### ISSUE THREAD

**Issue by tjiahen** [OSVR/Homebrew-OSVR#4]
Tried to install osvr but having this problem

```

  Could not find a package configuration file provided by "jsoncpp" with any
  of the following names:

    jsoncppConfig.cmake
    jsoncpp-config.cmake

  Add the installation prefix of "jsoncpp" to CMAKE_PREFIX_PATH or set
  "jsoncpp_DIR" to a directory containing one of the above files.  If
  "jsoncpp" provides a separate development package or SDK, be sure it has
  been installed.

```

**Comment by d235j** [comment]
Can you run `brew uninstall jsoncpp`, followed by `brew update`, `brew upgrade`, and then try installing again?

**Comment by tjiahen** [comment]
```
brew uninstall jsoncpp
Error: No such keg: /usr/local/Cellar/jsoncpp
```

after I `brew install jsoncpp` and `brew install hidapi`
It proceed with cmake

**Comment by tjiahen** [comment]
Now I am having this problem.

```
==> Checking out branch master
Synchronizing submodule url for 'submodules/hidapi'
Synchronizing submodule url for 'submodules/jsoncpp'
==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/osvr-core
==> make install
Last 15 lines from /Users/teejiahen/Library/Logs/Homebrew/osvr-core/02.make:
cd /tmp/osvr-core20151201-45520-1i8263d/build/src/osvr/Common && /usr/local/Library/ENV/4.3/clang++   -DEIGEN_MPL2_ONLY -DVRPN_USING_CMAKE=\"/tmp/osvr-core20151201-45520-1i8263d/build/vendor/vrpn/vrpn_Configure.h\" -DosvrCommon_EXPORTS -I/usr/local/include/opencv -I/usr/local/include -I/tmp/osvr-core20151201-45520-1i8263d/build/src -I/tmp/osvr-core20151201-45520-1i8263d/inc -isystem /usr/local/Cellar/jsoncpp/0.10.5/include -I/tmp/osvr-core20151201-45520-1i8263d/build/vendor/vrpn -I/tmp/osvr-core20151201-45520-1i8263d/vendor/vrpn -I/tmp/osvr-core20151201-45520-1i8263d/vendor/vrpn/atmellib -I/tmp/osvr-core20151201-45520-1i8263d/vendor/vrpn/quat -I/tmp/osvr-core20151201-45520-1i8263d/vendor/eigen-3.2.7  -arch i386 -arch x86_64 -fPIC    -W -Wall -Wextra -std=c++11 -o CMakeFiles/osvrCommon.dir/NetworkingSupport.cpp.o -c /tmp/osvr-core20151201-45520-1i8263d/src/osvr/Common/NetworkingSupport.cpp
[ 80%] Building CXX object src/osvr/Common/CMakeFiles/osvrCommon.dir/NormalizeDeviceDescriptor.cpp.o
cd /tmp/osvr-core20151201-45520-1i8263d/build/src/osvr/Common && /usr/local/Library/ENV/4.3/clang++   -DEIGEN_MPL2_ONLY -DVRPN_USING_CMAKE=\"/tmp/osvr-core20151201-45520-1i8263d/build/vendor/vrpn/vrpn_Configure.h\" -DosvrCommon_EXPORTS -I/usr/local/include/opencv -I/usr/local/include -I/tmp/osvr-core20151201-45520-1i8263d/build/src -I/tmp/osvr-core20151201-45520-1i8263d/inc -isystem /usr/local/Cellar/jsoncpp/0.10.5/include -I/tmp/osvr-core20151201-45520-1i8263d/build/vendor/vrpn -I/tmp/osvr-core20151201-45520-1i8263d/vendor/vrpn -I/tmp/osvr-core20151201-45520-1i8263d/vendor/vrpn/atmellib -I/tmp/osvr-core20151201-45520-1i8263d/vendor/vrpn/quat -I/tmp/osvr-core20151201-45520-1i8263d/vendor/eigen-3.2.7  -arch i386 -arch x86_64 -fPIC    -W -Wall -Wextra -std=c++11 -o CMakeFiles/osvrCommon.dir/NormalizeDeviceDescriptor.cpp.o -c /tmp/osvr-core20151201-45520-1i8263d/src/osvr/Common/NormalizeDeviceDescriptor.cpp
[ 80%] Building CXX object src/osvr/Common/CMakeFiles/osvrCommon.dir/OriginalSource.cpp.o
cd /tmp/osvr-core20151201-45520-1i8263d/build/src/osvr/Common && /usr/local/Library/ENV/4.3/clang++   -DEIGEN_MPL2_ONLY -DVRPN_USING_CMAKE=\"/tmp/osvr-core20151201-45520-1i8263d/build/vendor/vrpn/vrpn_Configure.h\" -DosvrCommon_EXPORTS -I/usr/local/include/opencv -I/usr/local/include -I/tmp/osvr-core20151201-45520-1i8263d/build/src -I/tmp/osvr-core20151201-45520-1i8263d/inc -isystem /usr/local/Cellar/jsoncpp/0.10.5/include -I/tmp/osvr-core20151201-45520-1i8263d/build/vendor/vrpn -I/tmp/osvr-core20151201-45520-1i8263d/vendor/vrpn -I/tmp/osvr-core20151201-45520-1i8263d/vendor/vrpn/atmellib -I/tmp/osvr-core20151201-45520-1i8263d/vendor/vrpn/quat -I/tmp/osvr-core20151201-45520-1i8263d/vendor/eigen-3.2.7  -arch i386 -arch x86_64 -fPIC    -W -Wall -Wextra -std=c++11 -o CMakeFiles/osvrCommon.dir/OriginalSource.cpp.o -c /tmp/osvr-core20151201-45520-1i8263d/src/osvr/Common/OriginalSource.cpp
[ 80%] Building CXX object src/osvr/Common/CMakeFiles/osvrCommon.dir/ParseAlias.cpp.o
cd /tmp/osvr-core20151201-45520-1i8263d/build/src/osvr/Common && /usr/local/Library/ENV/4.3/clang++   -DEIGEN_MPL2_ONLY -DVRPN_USING_CMAKE=\"/tmp/osvr-core20151201-45520-1i8263d/build/vendor/vrpn/vrpn_Configure.h\" -DosvrCommon_EXPORTS -I/usr/local/include/opencv -I/usr/local/include -I/tmp/osvr-core20151201-45520-1i8263d/build/src -I/tmp/osvr-core20151201-45520-1i8263d/inc -isystem /usr/local/Cellar/jsoncpp/0.10.5/include -I/tmp/osvr-core20151201-45520-1i8263d/build/vendor/vrpn -I/tmp/osvr-core20151201-45520-1i8263d/vendor/vrpn -I/tmp/osvr-core20151201-45520-1i8263d/vendor/vrpn/atmellib -I/tmp/osvr-core20151201-45520-1i8263d/vendor/vrpn/quat -I/tmp/osvr-core20151201-45520-1i8263d/vendor/eigen-3.2.7  -arch i386 -arch x86_64 -fPIC    -W -Wall -Wextra -std=c++11 -o CMakeFiles/osvrCommon.dir/ParseAlias.cpp.o -c /tmp/osvr-core20151201-45520-1i8263d/src/osvr/Common/ParseAlias.cpp
/tmp/osvr-core20151201-45520-1i8263d/src/osvr/Common/ParseAlias.cpp:77:16: error: no member named 'omitEndingLineFeed' in 'Json::FastWriter'
        writer.omitEndingLineFeed();
        ~~~~~~ ^
1 error generated.
make[2]: *** [src/osvr/Common/CMakeFiles/osvrCommon.dir/ParseAlias.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/osvr/Common/CMakeFiles/osvrCommon.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by tjiahen** [comment]
I guess it is not using `submodules/jsoncpp`, instead it uses jsoncpp from brew. It is a osvr-core issue?

http://diracprogram.org/doc/release-12/programmers/external_projects.html

**Comment by gching** [comment]
:+1: Been getting this problem too. I think it's because OSVR doesn't include jsoncpp as a submodule, or are you already handling this?

**Comment by gching** [comment]
Okay, figured it out! So whats happening is OSVR does not include jsoncpp as a submodule and you have to install it separately with brew. With that said, you need the most up to date version as older versions do not contain `omitEndingLineFeed`. Use `brew install jsoncpp --HEAD`.

@d235j I think we should add a dependency in the formula for jsoncpp. I can do it later when I'm not busy as it needs to be confirmed.

**Comment by godbyk** [comment]
Uninstalling, upgrading, and reinstalling `jsoncpp --HEAD` worked for me, too.

**Comment by d235j** [comment]
Yeah I need to fix the readme. A dependency won't help since you can't specify it as from head. Sorry about the delay on my end!

**Comment by CoolGames** [comment]
I got the OSVR HDK V1.3 for Christmas and 
am running Ubuntu Studio 15.10 on 13" MacBook Air (mid-2013).

I am not a recently trained programmer but an old school self-taught 1980's hacker.
I have never done json or cmake so even more of a babe in the woods.
I used synaptic to install all the jsoncpp indicated so not sure what --head is in Ubuntu land (yet).

Could not find a package configuration file provided by "jsoncpp" with any
  of the following names:

    jsoncppConfig.cmake
    jsoncpp-config.cmake

Getting this error from
 OSVR-Core-master using the commands in build directory

$ export OpenCV_DIR=/usr/share/OpenCV
$ export CMAKE_PREFIX_PATH=/usr/include/jsoncpp
$  cmake .. -DCMAKE_INSTALL_PREFIX=~/osvr

Status so far is for the record:

I got a Mini Display Port to HDMI at BestBuy for $30 and system settings ARandR can make the OSVR work as active display with resolution rotated to 1920x1080.

Changes occur with OSVR plugged in to Bus / Device number 
& observed values will be varied depending on devices on this system. 
I assume these are the OSVR HDK with IR accessory.
 
$ lsusb 
Bus 002 Device 002: ID 05e3:0617 Genesys Logic, Inc. 
Bus 001 Device 002: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 001 Device 006: ID 0572:1806 Conexant Systems (Rockwell), Inc. 
Bus 001 Device 008: ID 1532:0b00 Razer USA, Ltd

**Comment by rpavlik** [comment]
Looks like the instructions already made it into the readme. Also, I think I stopped using omitEndingLineFeed so that might help you too.

**Comment by gching** [comment]
**EDIT** Nevermind, just saw the new commit removing the additional step to install the head of jsoncpp :+1: 

@rpavlik sorry for talking here, but if omitEndingLineFeed is not used, does that mean we don't need need to use the head version of jsoncpp? If so, it would be easier to just add jsoncpp as a dependency rather than having to do both.

**Comment by rpavlik** [comment]
No need to apologize, I'm pretty sure that's what it means but I don't have a Mac to test it on to be sure.

**Comment by d235j** [comment]
@gching and @rpavlik I tested it and fixed it up — indeed we no longer need jsoncpp from head.
